routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes ::  Admin
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'isAdmin'], 'prefix'=> 'admin'], function() {
      
     Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');
     Route::resource('change-password', App\Http\Controllers\Admin\ChangePasswordController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);
     Route::resource('users', App\Http\Controllers\Admin\UserController::class, ['except' => []]);
     Route::resource('customers', App\Http\Controllers\Admin\CustomerController::class, ['except' => []]);
     Route::resource('products', App\Http\Controllers\Admin\ProductController::class, ['except' => []]);
     Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class, ['except' => []]);
     Route::resource('contacts', App\Http\Controllers\Admin\ContactRequestController::class, ['except' => []]);
     Route::resource('slider', App\Http\Controllers\Admin\SliderController::class, ['except' => []]);
     Route::resource('orders', App\Http\Controllers\Admin\OrderController::class, ['except' => []]);
     Route::resource('testimonial', App\Http\Controllers\Admin\TestimonialController::class, ['except' => []]);


     /* *Ajax Web Routes **/
     Route::post('/product-delete-image', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'deleteProductImage'])->name('product.image.delete');
     Route::post('/product-delete-variant', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'deleteProductVariant'])->name('product.variant.delete');
     Route::post('/order-payment-status', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderPaymentStatus'])->name('order.payment.status');
     Route::post('/order-delivery-status', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderdeliveryStatus'])->name('order.delivery.status');
    Route::get('/order-invoice/{id}', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderGenerateInvoice'])->name('order.invoice');
     

     
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Auth::routes(['verify' => true]); 

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/category/{slug}', [App\Http\Controllers\HomeController::class, 'category'])->name('category.all');
Route::get('/product/{slug}', [App\Http\Controllers\HomeController::class, 'productDetail'])->name('product.detail');
Route::post('/product-variation', [App\Http\Controllers\HomeController::class, 'variationPrice'])->name('product.variation');
Route::post('/add-to-cart', [App\Http\Controllers\HomeController::class, 'addToCart'])->name('product.cart');
Route::post('/remove-cart-item', [App\Http\Controllers\HomeController::class, 'removeCartItem'])->name('product.cart.remove');

Route::resource('contact-us', App\Http\Controllers\ContactusController::class, ['except' => ['create', 'edit', 'update', 'show', 'destroy']]);
Route::get('/about-us', [App\Http\Controllers\AboutusController::class, 'index'])->name('about-us');
Route::get('/services', [App\Http\Controllers\ServicesController::class, 'index'])->name('services');
Route::resource('checkout', App\Http\Controllers\CheckoutController::class, ['except' => ['create', 'edit', 'update', 'show', 'destroy']]);

Route::post('/payment', [App\Http\Controllers\PaymentController::class, 'payment'])->name('payment.make');
Route::post('/payment-form', [App\Http\Controllers\PaymentController::class, 'paymentForm'])->name('payment.form');
Route::get('/order-confirmation', [App\Http\Controllers\PaymentController::class, 'orderConfirmation'])->name('order.confirmation');

include('admin.php');

include('customer.php');

resources/views/about-us.blade.php
@extends('layouts.front')
@section('title', 'About')
@section('content')

  <!-- about section -->
  <section class="about spad">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12">
            <!-- Section Heading-->
            <div class="section-heading text-center">
              <h3>About Us</h3>
            </div>
          </div>
        </div>
        <div class="row mrgn-top-50">
          <div class="col-md-6 col-lg-6">
            <img src="{{ asset('assets/site/img/about.jpg') }}">
          </div>
          <div class="col-md-6 col-lg-6">
            <div class="about_item">
              <h4>Who We Are ?</h4>
              <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
            </div>
            <div class="about_item">
              <h4>Who We Do ?</h4>
              <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
            </div>
            <div class="about_item">
              <h4>Why Choose Us</h4>
              <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. </p>
            </div>
          </div> 
          </div>
        </div>
      </div>
  </section>
  <!-- / about section -->
   <!-- Testimonial -->
  <section id="testimonial"> 
    <div id="myCarouseltesti" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarouseltesti" data-slide-to="0" class="active"></li>
        <li data-target="#myCarouseltesti" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <div class="testimonial-single">
            <img class="testimonial-img" src="{{ asset('assets/site/img/thumbnail.jpg') }}" alt="testimonial img">
              <span class="fa fa-quote-left testimonial-quote"></span>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt distinctio omnis possimus, facere, quidem qui!consectetur adipisicing elit. Sunt distinctio omnis possimus, facere, quidem qui.</p>
              <div class="testimonial-info">
                <p>KEVIN MEYER</p>
              </div>
          </div>
        </div>

        <div class="item">
          <div class="testimonial-single">
            <img class="testimonial-img" src="{{ asset('assets/site/img/thumbnail.jpg') }}" alt="testimonial img">
              <span class="fa fa-quote-left testimonial-quote"></span>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt distinctio omnis possimus, facere, quidem qui!consectetur adipisicing elit. Sunt distinctio omnis possimus, facere, quidem qui.</p>
              <div class="testimonial-info">
                <p>KEVIN MEYER</p>
              </div>
          </div>
        </div>
      </div>
    </div> 
  </section>
  <!-- / Testimonial -->

@endsection

resources/views/contact-us.blade.php
@extends('layouts.front')
@section('title', 'Contact')
@section('content')

 <!-- Contact Section Begin -->
  <section class="contact spad">
      <div class="container">
          <div class="row">
              <div class="col-lg-6 col-md-6">
                  <div class="contact_text">
                      <div class="section-title">
                          <h2>Contact Us</h2>
                          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
                      </div>
                      <ul>
                          <li>
                              <h4>America</h4>
                              <p>25 Astor Road, NY 12303, USA <br />+1 212-123-4589</p>
                          </li>
                          <li>
                              <h4>France</h4>
                              <p>109 Avenue Leon, 63 Clermont-Ferrand <br />+12 345-423-9893</p>
                          </li>
                      </ul>
                  </div>
              </div>
              <div class="col-lg-6 col-md-6">
                  <div class="contact_form">
                      <form action="{{ route('contact-us.store') }}" method="POST">
                        @csrf
                          
                          <div class="row">
                              <div class="col-lg-6">
                                  <input type="text" name="name" value="{{ old('name') }}" placeholder="Name" required>

                                    @error('name')
                                       <span class="invalid-feedback" role="alert">
                                          <strong>{{ $message }}</strong>
                                       </span>
                                    @enderror

                              </div>
                              <div class="col-lg-6">
                                  <input type="email" name="email" value="{{ old('email') }}" placeholder="Email" required>

                                    @error('email')
                                       <span class="invalid-feedback" role="alert">
                                          <strong>{{ $message }}</strong>
                                       </span>
                                    @enderror

                              </div>
                              <div class="col-lg-12">
                                  <textarea placeholder="Message" name="message" required>{{ old('message') }}</textarea>

                                    @error('message')
                                       <span class="invalid-feedback" role="alert">
                                          <strong>{{ $message }}</strong>
                                       </span>
                                    @enderror

                                  {!! RecaptchaV3::initJs() !!}
                                  {!! RecaptchaV3::field('contact-us') !!}
                                 
                                 <button type="submit" class="site-btn">Send Message</button>

                              </div>
                          </div>

                      </form>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <!-- Contact Section End -->
  <!-- Map Begin -->
  <div class="map">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d111551.9926412813!2d-90.27317134641879!3d38.606612219170856!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x54eab584e432360b%3A0x1c3bb99243deb742!2sUnited%20States!5e0!3m2!1sen!2sbd!4v1597926938024!5m2!1sen!2sbd" height="500" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
  </div>
  <!-- Map End -->

@endsection

resources/views/home.blade.php
@extends('layouts.front')
@section('title', 'Home')
@section('content')

  <!-- Start slider -->
  <section id="slider">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        @if(!empty($slider))
        @foreach($slider as $key => $value)
        <div class="item @if($key==0) active @endif">
          <img src="{{ displayBanner($value->slide) }}" alt="slide 1" class="w-100">
        </div>
        @endforeach
        @endif

      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="fa fa-angle-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="fa fa-angle-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </section>
  <!-- / slider -->
  <!-- Products section -->
  <section id="product">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="product-area">
              <div class="product-inner">
                <h2 class="section-title">Best Sellers</h2>
                <div class="row">
                  @if(!empty($products))
                    @foreach($products as $key => $value)
                      <div class="col-xs-6 col-sm-3 col-lg-3 product-catg">
                        <figure>
                          <div class="relative">
                            <a class="product-img" href="{{ route('product.detail', Str::slug($value->name) ) }}">
                              <img src="{{ displayBanner($value->thumbnail_img) }}" alt="{{ $value->slug }}" style="height:250px; width:300px;">
                            </a>
                            <a class="add-card-btn" href="{{ route('product.detail', $value->slug ) }}">Buy Now</a>
                          </div>
                          <figcaption>
                            <h4 class="product-title">
                              <a href="{{ route('product.detail', $value->slug ) }}" alt="{{ $value->slug }}">{{ $value->name }}</a>
                            </h4>
                            <span class="product-price">{{ trans('app.currency') }}{{ $value->purchase_price }}</span>
                          </figcaption>
                        </figure>
                      </div>
                    @endforeach
                  @endif
                </div>
              </div>
            </div>       
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- / Products section -->
  <!-- banner section -->
  <section id="banner">
    <div class="container">
      <div class="row">
        <div class="col-md-12">        
          <div class="row">
            <div class="banner-area">
            <a href="#"><img src="{{ asset('assets/site/img/ad-banner.jpg') }}" alt="ad-banner img"></a>
          </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Category section -->
  <section id="category">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <div class="product-area">
              <div class="product-inner">
                <h2 class="section-title">Shop By Category</h2>
                <div class="carousel row" data-flickity='{"cellAlign": "left", "lazyLoad": true, "wrapAround": true, "pageDots": false, "initialIndex": 2, "autoPlay": false }'>
                  @if(!empty($categories))
                    @foreach($categories as $key => $value)
                      <div class="carousel-cell"> 
                        <figure>
                          <div class="relative">
                            <a class="product-img" href="{{ route('category.all', $value->slug) }}">
                              <img src="{{ displayBanner($value->banner) }}" alt="{{ $value->slug }}" style="height:250px; width:300px;">
                          </a>
                          </div>
                          <figcaption>
                            <h4 class="product-title text-center"><a href="#">{{ $value->name }}</a></h4>
                          </figcaption>
                        </figure>    
                      </div>
                    @endforeach
                  @endif
                 
                </div>
              </div>
            </div>       
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- / Products section -->
  <!-- Testimonial -->
  <section id="testimonial"> 
    <div id="myCarouseltesti" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarouseltesti" data-slide-to="0" class="active"></li>
        <li data-target="#myCarouseltesti" data-slide-to="1"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        @if(!empty($testimonials))
          @foreach($testimonials as $key => $value)
            <div class="item @if($key==0) active @endif">
              <div class="testimonial-single">
                <img class="testimonial-img" src="{{ displayBanner($value->image) }}" alt="testimonial img">
                  <span class="fa fa-quote-left testimonial-quote"></span>
                  <p>{{ $value->description }}</p>
                  <div class="testimonial-info">
                    <p>{{ $value->name }}</p>
                  </div>
              </div>
            </div>
          @endforeach
        @endif

      </div>
    </div> 
  </section>
  <!-- / Testimonial -->
  <!-- / Footer Features -->
  <div class="footer-features hidden-xs">
    <div class="container">
      <ul class="features-list d-flex justify-content-between">
        <li class="feature text-center">
          <img src="{{ asset('assets/site/img/payment-security.png') }}">
          <span class="feature-text">100% Payment <br>Secured</span>
        </li>
        <li class="feature text-center">
          <img src="{{ asset('assets/site/img/wallet.png') }}">
          <span class="feature-text">Support lots <br>of Payments</span>
        </li>
        <li class="feature text-center">
          <img src="{{ asset('assets/site/img/support.png') }}">
          <span class="feature-text">24 hours/7 days <br>Support</span>
        </li>
        <li class="feature text-center">
          <img src="{{ asset('assets/site/img/truck.png') }}">
          <span class="feature-text">Free Delivery <br>with $50</span>
        </li>
        <li class="feature text-center">
          <img src="{{ asset('assets/site/img/discount.png') }}">
          <span class="feature-text">Best Price <br>Guaranteed</span>
        </li>
      </ul>
    </div>
  </div>

@endsection

resources/views/services.blade.php
@extends('layouts.front')
@section('title', 'Services')
@section('content')

<!-- Services section -->
  <section class="service_plan_area spad">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12">
            <!-- Section Heading-->
            <div class="section-heading text-center">
              <h3>Our Services</h3>
              <p>Select your favourite service from below boxes</p>
              <div class="line"></div>
            </div>
          </div>
        </div>
        <div class="row justify-content-center">
          <!-- Single Price Plan Area-->
          <div class="col-12 col-sm-8 col-md-6 col-lg-4">
            <div class="single_service_plan" >
              <div class="title">
                <h3>Service Name</h3>
                <p>Start a trial</p>
                <div class="line"></div>
              </div>
              <div class="price">
                <h4>$0</h4>
              </div>
              <div class="description">
                <p><i class="fa fa-check"></i>Duration: 7days</p>
                <p><i class="fa fa-check"></i>10 Features</p>
                <p><i class="fa fa-times"></i>No Hidden Fees</p>
                <p><i class="fa fa-times"></i>100+ Video Tuts</p>
                <p><i class="fa fa-times"></i>No Tools</p>
              </div>
              <div class="button"><a class="browse-btn" href="#">Get Started</a></div>
            </div>
          </div>
          <!-- Single Price Plan Area-->
          <div class="col-12 col-sm-8 col-md-6 col-lg-4">
            <div class="single_service_plan active">
              <!-- Side Shape-->
              <div class="side-shape"><img src="{{ asset('assets/site/img/popular-service.png') }}" alt=""></div>
              <div class="title"><span>Selected</span>
                <h3>Service Name</h3>
                <p>For Small Organization</p>
                <div class="line"></div>
              </div>
              <div class="price">
                <h4>$9.99</h4>
              </div>
              <div class="description">
                <p><i class="fa fa-check"></i>Duration: 3 Month</p>
                <p><i class="fa fa-check"></i>50 Features</p>
                <p><i class="fa fa-check"></i>No Hidden Fees</p>
                <p><i class="fa fa-check"></i>150+ Video Tuts</p>
                <p><i class="fa fa-times"></i>5 Tools</p>
              </div>
              <div class="button"><a class="browse-btn" href="#">Get Started</a></div>
            </div>
          </div>
          <!-- Single Price Plan Area-->
          <div class="col-12 col-sm-8 col-md-6 col-lg-4">
            <div class="single_service_plan">
              <div class="title">
                <h3>Service Name</h3>
                <p>Unlimited Possibilities</p>
                <div class="line"></div>
              </div>
              <div class="price">
                <h4>$49.99</h4>
              </div>
              <div class="description">
                <p><i class="fa fa-check"></i>Duration: 1 year</p>
                <p><i class="fa fa-check"></i>Unlimited Features</p>
                <p><i class="fa fa-check"></i>No Hidden Fees</p>
                <p><i class="fa fa-check"></i>Unlimited Video Tuts</p>
                <p><i class="fa fa-check"></i>Unlimited Tools</p>
              </div>
              <div class="button"><a class="browse-btn" href="#">Get Started</a></div>
            </div>
          </div>
        </div>
      </div>
    </section>
  <!-- / Services section -->

@endsection