routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes ::  Admin
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'isAdmin'], 'prefix'=> 'admin'], function() {
      
     Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');
     Route::resource('change-password', App\Http\Controllers\Admin\ChangePasswordController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);
     Route::resource('users', App\Http\Controllers\Admin\UserController::class, ['except' => []]);
     Route::resource('customers', App\Http\Controllers\Admin\CustomerController::class, ['except' => []]);
     Route::resource('products', App\Http\Controllers\Admin\ProductController::class, ['except' => []]);
     Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class, ['except' => []]);
     Route::resource('contacts', App\Http\Controllers\Admin\ContactRequestController::class, ['except' => []]);
     Route::resource('slider', App\Http\Controllers\Admin\SliderController::class, ['except' => []]);
     Route::resource('orders', App\Http\Controllers\Admin\OrderController::class, ['except' => []]);
     Route::resource('testimonial', App\Http\Controllers\Admin\TestimonialController::class, ['except' => []]);


     /* *Ajax Web Routes **/
     Route::post('/product-delete-image', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'deleteProductImage'])->name('product.image.delete');
     Route::post('/product-delete-variant', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'deleteProductVariant'])->name('product.variant.delete');
     Route::post('/order-payment-status', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderPaymentStatus'])->name('order.payment.status');
     Route::post('/order-delivery-status', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderdeliveryStatus'])->name('order.delivery.status');
    Route::get('/order-invoice/{id}', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderGenerateInvoice'])->name('order.invoice');
     

     
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Auth::routes(['verify' => true]); 

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/category/{slug}', [App\Http\Controllers\HomeController::class, 'category'])->name('category.all');
Route::get('/product/{slug}', [App\Http\Controllers\HomeController::class, 'productDetail'])->name('product.detail');
Route::post('/product-variation', [App\Http\Controllers\HomeController::class, 'variationPrice'])->name('product.variation');
Route::post('/add-to-cart', [App\Http\Controllers\HomeController::class, 'addToCart'])->name('product.cart');
Route::post('/remove-cart-item', [App\Http\Controllers\HomeController::class, 'removeCartItem'])->name('product.cart.remove');

Route::resource('contact-us', App\Http\Controllers\ContactusController::class, ['except' => ['create', 'edit', 'update', 'show', 'destroy']]);
Route::get('/about-us', [App\Http\Controllers\AboutusController::class, 'index'])->name('about-us');
Route::get('/services', [App\Http\Controllers\ServicesController::class, 'index'])->name('services');
Route::resource('checkout', App\Http\Controllers\CheckoutController::class, ['except' => ['create', 'edit', 'update', 'show', 'destroy']]);

Route::post('/payment', [App\Http\Controllers\PaymentController::class, 'payment'])->name('payment.make');
Route::post('/payment-form', [App\Http\Controllers\PaymentController::class, 'paymentForm'])->name('payment.form');
Route::get('/order-confirmation', [App\Http\Controllers\PaymentController::class, 'orderConfirmation'])->name('order.confirmation');

include('admin.php');

include('customer.php');

resources/views/admin/_dashboard.blade.php
@extends('admin.layouts._master')
@section('title', 'Dashboard')
@section('content')
<!-- Main content -->
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box">
               <span class="info-box-icon bg-info elevation-1"><i class="fas fa-flag"></i></span>
               <div class="info-box-content">
                  <span class="info-box-text">Today Orders</span>
                  <span class="info-box-number">
                   {{ $todayOrder }}
                  </span>
               </div>
               <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
         </div>
         <!-- /.col -->
         <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
               <span class="info-box-icon bg-danger elevation-1"><i class="fas fa-shopping-cart"></i></span>
               <div class="info-box-content">
                  <span class="info-box-text">Orders</span>
                  <span class="info-box-number">{{ $orders }}</span>
               </div>
               <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
         </div>
         <!-- /.col -->
         <!-- fix for small devices only -->
         <div class="clearfix hidden-md-up"></div>
         <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
               <span class="info-box-icon bg-success elevation-1"><i class="fas fa-shopping-cart"></i></span>
               <div class="info-box-content">
                  <span class="info-box-text">Products</span>
                  <span class="info-box-number">{{ $products }}</span>
               </div>
               <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
         </div>
         <!-- /.col -->
         <div class="col-12 col-sm-6 col-md-3">
            <div class="info-box mb-3">
               <span class="info-box-icon bg-warning elevation-1"><i class="fas fa-users"></i></span>
               <div class="info-box-content">
                  <span class="info-box-text">Customers</span>
                  <span class="info-box-number">{{ $users }}</span>
               </div>
               <!-- /.info-box-content -->
            </div>
            <!-- /.info-box -->
         </div>
         <!-- /.col -->
      </div>
      <div class="row">
         <div class="col-12 col-sm-6 col-md-12">
            <div class="card">
               <div class="card-header border-transparent">
                  <h3 class="card-title">Latest Orders</h3>
               </div>
               <!-- /.card-header -->
               <div class="card-body p-0">
                  <div class="table-responsive">
                     <table class="table m-0">
                        <thead>
                           <tr>
                              <th>#</th>
                              <th>Order Code</th>
                              <th>Customer</th>
                              <th>Num. of Products</th>
                              <th>Amount</th>
                              <th>Payment Status</th>
                              <th>Delivery Status</th>
                           </tr>
                        </thead>
                        <tbody>
                           @if(!empty($latestOrders) )
                              @php $counter = 0; @endphp
                              @foreach($latestOrders as $key => $value)
                              <tr>
                                 <td>{{ ++$counter }}</td>
                                 <td>
                                    <a href="javascript:;">{{ $value->code }}</a>
                                 </td>
                                 <td>{{ $value->customer['first_name'] }} {{ $value->customer['last_name']}}</td>
                                 <td>{{ count($value->orderDetail) }}</td>
                                 <td>£{{ $value->grand_total }}</td>
                                 <td class="text-center">
                                    @if($value->payment_status == 'Paid')
                                     <span class="badge badge-success">{{ $value->payment_status}}</span>
                                    @else
                                    <span class="badge badge-danger">{{ $value->payment_status}}</span>
                                    @endif
                                 </td>
                                 <td class="text-center">
                                    @if($value->delivery_status == 'Pending')
                                     <span class="badge badge-danger">{{ $value->delivery_status}}</span>
                                    @elseif($value->delivery_status == 'Shipped')
                                    <span class="badge badge-success">{{ $value->delivery_status}}</span>
                                    @else
                                    <span class="badge badge-warning">{{ $value->delivery_status}}</span>
                                    @endif
                                 </td>
                              </tr>
                              @endforeach
                           @endif
                        
                        </tbody>
                     </table>
                  </div>
                  <!-- /.table-responsive -->
               </div>
               <!-- /.card-body -->
               <div class="card-footer clearfix">
                  <a href="{{ route('orders.index') }}" class="btn btn-sm btn-secondary float-right">View All Orders</a>
               </div>
               <!-- /.card-footer -->
            </div>
         </div>
      </div>
   </div>
   <!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection