routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes ::  Admin
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'isAdmin'], 'prefix'=> 'admin'], function() {
      
     Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');
     Route::resource('change-password', App\Http\Controllers\Admin\ChangePasswordController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);
     Route::resource('users', App\Http\Controllers\Admin\UserController::class, ['except' => []]);
     Route::resource('customers', App\Http\Controllers\Admin\CustomerController::class, ['except' => []]);
     Route::resource('products', App\Http\Controllers\Admin\ProductController::class, ['except' => []]);
     Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class, ['except' => []]);
     Route::resource('contacts', App\Http\Controllers\Admin\ContactRequestController::class, ['except' => []]);
     Route::resource('slider', App\Http\Controllers\Admin\SliderController::class, ['except' => []]);
     Route::resource('orders', App\Http\Controllers\Admin\OrderController::class, ['except' => []]);
     Route::resource('testimonial', App\Http\Controllers\Admin\TestimonialController::class, ['except' => []]);


     /* *Ajax Web Routes **/
     Route::post('/product-delete-image', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'deleteProductImage'])->name('product.image.delete');
     Route::post('/product-delete-variant', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'deleteProductVariant'])->name('product.variant.delete');
     Route::post('/order-payment-status', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderPaymentStatus'])->name('order.payment.status');
     Route::post('/order-delivery-status', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderdeliveryStatus'])->name('order.delivery.status');
    Route::get('/order-invoice/{id}', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderGenerateInvoice'])->name('order.invoice');
     

     
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Auth::routes(['verify' => true]); 

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/category/{slug}', [App\Http\Controllers\HomeController::class, 'category'])->name('category.all');
Route::get('/product/{slug}', [App\Http\Controllers\HomeController::class, 'productDetail'])->name('product.detail');
Route::post('/product-variation', [App\Http\Controllers\HomeController::class, 'variationPrice'])->name('product.variation');
Route::post('/add-to-cart', [App\Http\Controllers\HomeController::class, 'addToCart'])->name('product.cart');
Route::post('/remove-cart-item', [App\Http\Controllers\HomeController::class, 'removeCartItem'])->name('product.cart.remove');

Route::resource('contact-us', App\Http\Controllers\ContactusController::class, ['except' => ['create', 'edit', 'update', 'show', 'destroy']]);
Route::get('/about-us', [App\Http\Controllers\AboutusController::class, 'index'])->name('about-us');
Route::get('/services', [App\Http\Controllers\ServicesController::class, 'index'])->name('services');
Route::resource('checkout', App\Http\Controllers\CheckoutController::class, ['except' => ['create', 'edit', 'update', 'show', 'destroy']]);

Route::post('/payment', [App\Http\Controllers\PaymentController::class, 'payment'])->name('payment.make');
Route::post('/payment-form', [App\Http\Controllers\PaymentController::class, 'paymentForm'])->name('payment.form');
Route::get('/order-confirmation', [App\Http\Controllers\PaymentController::class, 'orderConfirmation'])->name('order.confirmation');

include('admin.php');

include('customer.php');

resources/views/admin/partials/inc/_foot.blade.php
    <!-- jQuery -->
    <script src="{{ asset('assets/plugins/jquery/jquery.min.js') }}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{{ asset('assets/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{{ asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <!-- ChartJS -->
    <script src="{{ asset('assets/plugins/chart.js/Chart.min.js') }}"></script>
    <!-- Sparkline -->
    <script src="{{ asset('assets/plugins/sparklines/sparkline.js') }}"></script>
    <!-- JQVMap -->
    <script src="{{ asset('assets/plugins/jqvmap/jquery.vmap.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/jqvmap/maps/jquery.vmap.usa.js') }}"></script>
    <!-- jQuery Knob Chart -->
    <script src="{{ asset('assets/plugins/jquery-knob/jquery.knob.min.js') }}"></script>
    <!-- daterangepicker -->
    <script src="{{ asset('assets/plugins/moment/moment.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/daterangepicker/daterangepicker.js') }}"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="{{ asset('assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
    
    <!-- Summernote -->
    <script src="{{ asset('assets/plugins/summernote/summernote-bs4.min.js') }}"></script>

    <!-- overlayScrollbars -->
    <script src="{{ asset('assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
    <!-- AdminLTE App -->
    <script src="{{ asset('assets/dist/js/adminlte.js') }}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <!-- AdminLTE for demo purposes -->
    <script src="{{ asset('assets/dist/js/demo.js') }}"></script>
    <script src="{{ asset('assets/plugins/ekko-lightbox/ekko-lightbox.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/filterizr/jquery.filterizr.min.js') }}"></script>
   
    <!--- Datatable JS start-->
    <script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <!--- Datatable Js end -->
    
    <!-- Tempusdominus Bootstrap 4 -->
   <script src="{{ asset('assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-switch/js/bootstrap-switch.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/sweetalert2/sweetalert2.min.js') }}"></script>
    <!-- Toastr -->
    <script src="{{ asset('assets/plugins/toastr/toastr.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/select2/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('assets/js/jquery-ui.js') }}"></script>
     <script src="{{ asset('assets/js/admin-script.js') }}"></script>

resources/views/admin/partials/inc/_head.blade.php
<link rel="stylesheet" href="{{ asset('assets/plugins/fontawesome-free/css/all.min.css') }}">
     <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
      <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
      <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
      <!-- JQVMap -->
      <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('assets/dist/css/adminlte.min.css') }}">
      <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
      <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('assets/plugins/daterangepicker/daterangepicker.css') }}">
    
    <!--- Datatables--->
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <!--- Datatbales End --->

    <link rel="stylesheet" href="{{ asset('assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/toastr/toastr.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/select2/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/plugins/ekko-lightbox/ekko-lightbox.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/jquery-ui.css') }}">

    <link rel="stylesheet" href="{{ asset('assets//plugins/summernote/summernote-bs4.min.css') }}">

resources/views/admin/partials/inc/_menu.blade.php
<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
    <li class="nav-item has-treeview">
        <a href="{{ route('admin.dashboard') }}" class="nav-link {{ areActiveRoutes(['admin.dashboard']) }}">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
                Dashboard
                <i class="fas {{ areActiveRoutesIcon(['admin.dashboard']) }} right"></i>
            </p>
        </a> 
    </li>
    <li class="nav-item has-treeview">
        <a href="{{ route('customers.index') }}" class="nav-link {{ areActiveRoutes(['customers.index', 'customers.show']) }}">
            <i class="nav-icon fas fa-users"></i>
            <p>Customers 
                <i class="fas {{ areActiveRoutesIcon(['customers.index', 'customers.show']) }} right"></i>
            </p>
        </a> 
    </li>
    <li class="nav-item has-treeview {{ areActiveRoutesMenuOpen(['products.index', 'products.create', 'products.edit', 'categories.index','categories.index','categories.create','categories.edit']) }}">
        <a href="#" class="nav-link {{ areActiveRoutes(['products.index', 'products.create', 'products.edit','categories.index','categories.create','categories.edit']) }}">
            <i class="nav-icon fas fa-shopping-cart"></i>
            <p>Products<i class="fas fa-angle-left right"></i></p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a href="{{ route('products.create') }}" class="nav-link {{ areActiveRoutes(['products.create']) }}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Add Product</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('products.index') }}" class="nav-link {{ areActiveRoutes(['products.index', 'products.edit']) }}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>All Products</p>
                </a>
            </li>
            <li class="nav-item">
                <a href="{{ route('categories.index') }}" class="nav-link {{ areActiveRoutes(['categories.index','categories.create','categories.edit']) }}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Category</p>
                </a>
            </li>
        </ul>
    </li>

    <li class="nav-item has-treeview {{ areActiveRoutesMenuOpen(['orders.index','orders.show']) }}">
        <a href="#" class="nav-link {{ areActiveRoutes(['orders.index','orders.show']) }}">
            <i class="nav-icon fas fa-shopping-cart"></i>
            <p>Sales<i class="fas fa-angle-left right"></i></p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a href="{{ route('orders.index') }}" class="nav-link {{ areActiveRoutes(['orders.index', 'orders.show']) }}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>All Orders</p>
                </a>
            </li>
        </ul>
    </li>

    <li class="nav-item has-treeview">
        <a href="{{ route('contacts.index') }}" class="nav-link {{ areActiveRoutes(['contacts.index', 'contacts.create', 'contacts.edit']) }}">
            <i class="nav-icon fas fa-envelope"></i>
            <p>Contact Request 
                <i class="fas {{ areActiveRoutesIcon(['contacts.index', 'contacts.create', 'contacts.edit']) }} right"></i>
            </p>
        </a> 
    </li>

    <li class="nav-item has-treeview">
        <a href="{{ route('testimonial.index') }}" class="nav-link {{ areActiveRoutes(['testimonial.index', 'testimonial.create', 'testimonial.edit']) }}">
            <i class="nav-icon fa fa-comments"></i>
            <p>Testimonial
                <i class="fas {{ areActiveRoutesIcon(['testimonial.index', 'testimonial.create', 'testimonial.edit']) }} right"></i>
            </p>
        </a> 
    </li>

    <li class="nav-item has-treeview {{ areActiveRoutesMenuOpen(['change-password.index']) }}">
        <a href="#" class="nav-link {{ areActiveRoutes(['change-password.index']) }}">
            <i class="nav-icon fas fa-cog"></i>
            <p>Account settings <i class="fas fa-angle-left right"></i></p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a href="{{ route('change-password.index') }}" class="nav-link {{ areActiveRoutes(['change-password.index']) }}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Change Password</p>
                </a>
            </li>
        </ul>
    </li>

    <li class="nav-item has-treeview {{ areActiveRoutesMenuOpen(['slider.index', 'slider.create', 'slider.edit']) }}">
        <a href="#" class="nav-link {{ areActiveRoutes(['slider.index','slider.create', 'slider.edit']) }}">
            <i class="nav-icon fas fa-plus"></i>
            <p>General settings <i class="fas fa-angle-left right"></i></p>
        </a>
        <ul class="nav nav-treeview">
            <li class="nav-item">
                <a href="{{ route('slider.index') }}" class="nav-link {{ areActiveRoutes(['slider.index','slider.create', 'slider.edit']) }}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>Slider</p>
                </a>
            </li>
        </ul>
    </li>

    <li class="nav-item has-treeview">
        <a href="{{ route('logout') }}"
            onclick="event.preventDefault();
             document.getElementById('logout-form').submit();"
            class="nav-link">
            <i class="nav-icon fas fa-sign-out-alt"></i>
            <p>
                Logout
            </p>
        </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
            @csrf
        </form>
    </li>
</ul>