routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes ::  Admin
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth', 'isAdmin'], 'prefix'=> 'admin'], function() {
      
     Route::get('dashboard', [App\Http\Controllers\Admin\DashboardController::class, 'index'])->name('admin.dashboard');
     Route::resource('change-password', App\Http\Controllers\Admin\ChangePasswordController::class, ['except' => ['show', 'edit', 'destroy','update', 'create']]);
     Route::resource('users', App\Http\Controllers\Admin\UserController::class, ['except' => []]);
     Route::resource('customers', App\Http\Controllers\Admin\CustomerController::class, ['except' => []]);
     Route::resource('products', App\Http\Controllers\Admin\ProductController::class, ['except' => []]);
     Route::resource('categories', App\Http\Controllers\Admin\CategoryController::class, ['except' => []]);
     Route::resource('contacts', App\Http\Controllers\Admin\ContactRequestController::class, ['except' => []]);
     Route::resource('slider', App\Http\Controllers\Admin\SliderController::class, ['except' => []]);
     Route::resource('orders', App\Http\Controllers\Admin\OrderController::class, ['except' => []]);
     Route::resource('testimonial', App\Http\Controllers\Admin\TestimonialController::class, ['except' => []]);


     /* *Ajax Web Routes **/
     Route::post('/product-delete-image', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'deleteProductImage'])->name('product.image.delete');
     Route::post('/product-delete-variant', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'deleteProductVariant'])->name('product.variant.delete');
     Route::post('/order-payment-status', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderPaymentStatus'])->name('order.payment.status');
     Route::post('/order-delivery-status', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderdeliveryStatus'])->name('order.delivery.status');
    Route::get('/order-invoice/{id}', [App\Http\Controllers\Admin\CommonAjaxHandleController::class, 'orderGenerateInvoice'])->name('order.invoice');
     

     
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Auth::routes(['verify' => true]); 

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/category/{slug}', [App\Http\Controllers\HomeController::class, 'category'])->name('category.all');
Route::get('/product/{slug}', [App\Http\Controllers\HomeController::class, 'productDetail'])->name('product.detail');
Route::post('/product-variation', [App\Http\Controllers\HomeController::class, 'variationPrice'])->name('product.variation');
Route::post('/add-to-cart', [App\Http\Controllers\HomeController::class, 'addToCart'])->name('product.cart');
Route::post('/remove-cart-item', [App\Http\Controllers\HomeController::class, 'removeCartItem'])->name('product.cart.remove');

Route::resource('contact-us', App\Http\Controllers\ContactusController::class, ['except' => ['create', 'edit', 'update', 'show', 'destroy']]);
Route::get('/about-us', [App\Http\Controllers\AboutusController::class, 'index'])->name('about-us');
Route::get('/services', [App\Http\Controllers\ServicesController::class, 'index'])->name('services');
Route::resource('checkout', App\Http\Controllers\CheckoutController::class, ['except' => ['create', 'edit', 'update', 'show', 'destroy']]);

Route::post('/payment', [App\Http\Controllers\PaymentController::class, 'payment'])->name('payment.make');
Route::post('/payment-form', [App\Http\Controllers\PaymentController::class, 'paymentForm'])->name('payment.form');
Route::get('/order-confirmation', [App\Http\Controllers\PaymentController::class, 'orderConfirmation'])->name('order.confirmation');

include('admin.php');

include('customer.php');

app/Models/Testimonial.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Testimonial extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'image',
        'description'
    ];
}

app/Http/Controllers/Admin/TestimonialController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Testimonial;
use App\Http\Traits\FileTrait;

class TestimonialController extends Controller
{   
    use FileTrait;

    private $model_name;

    /**
     * Create a new controller instance.
     * 
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->model_name = trans('app.model.testimonial');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $testimonials = Testimonial::all();
        return view('admin.testimonials._index', compact('testimonials') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.testimonials._create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Testimonial $testimonial)
    {
        if($request->hasFile('image')) {
            $data = $this->uploadImage($request->file('image'));
            if(!empty($data)) {
                $testimonial = Testimonial::create(
                    array_merge(
                        $request->all(),
                        ['image' => $data['file_path'] ]
                    )
                );
                if( ! $testimonial)
                    return back()->with('error', trans('messages.failed'));
                return back()->with('success', trans('messages.created', ['model' => $this->model_name]));
            }
            return back()->with('error', trans('messages.failed'));

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Testimonial $testimonial)
    {
        return view('admin.testimonials.edit', compact('testimonial'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/testimonials/_create.blade.php
@extends('admin.layouts._master')

@section('title', 'Add Testimonial')

@section('content')

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-md-6">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">@yield('title')</h3>

        </div>
        
        {!! Form::open(['route' => 'testimonial.store', 'files' => true]) !!}
        <div class="card-body">
            
            <div class="form-group">
               {!! Form::label('name', 'Name', ['class' => 'required']) !!}
               <sup class="text-danger">[Required]</sup>
               {!! Form::text('name', old('name'), array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
                @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
              {!! Form::label('image', 'Image', ['class' => 'required']) !!}
              <sup class="text-danger">[Required]</sup>
              {!! Form::file('image', array_merge(['class' => 'form-control'], ['required' => true] ) ) !!}
              @error('image')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
            </div>

            <div class="form-group">
	            {!! Form::label('description', 'Feedback', ['class' => 'awesome']) !!} 
              <sup class="text-danger">[Required]</sup>
	            {!! Form::textarea('description', old('description'), array_merge(['class' => 'form-control'], ['required' => true], ['rows' => 4] ) ) !!}
	             @error('description')
	                  <span class="invalid-feedback" role="alert">
	                      <strong>{{ $message }}</strong>
	                  </span>
	              @enderror
          </div>
        </div>
        <div class="card-footer">
            {!! Form::submit(trans('app.buttons.save'), ['class' => 'btn btn-success']) !!}
            {!! link_to_route('testimonial.index',  trans('app.buttons.cancel'), $parameters = [],  ['class' => 'btn btn-secondary']) !!} 
            {!! Form::close() !!}
        </div>

      </div>
      <!-- /.card -->
    </div>
   
  </div>

</section>
<!-- /.content -->

@endsection

resources/views/admin/testimonials/_index.blade.php
@extends('admin.layouts._master')

@section('title', 'Testimonial')

@section('content')
<section class="content">
   <div class="container-fluid">
      <div class="row">
         <div class="col-12">
            <div class="card card-primary card-outline">
               <div class="card-header">
                  <a style="float: right;" href="{{ route('testimonial.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Add Testimonial</a>
               </div>
               <!-- /.card-header -->
               <div class="card-body">
                  <table id="example1" class="table table-bordered table-striped">
                     <thead>
                        <tr>
                           <th>S.No</th>
                           <th>Name</th>
                           <th>Image</th>
                           <th>Feedback</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                     @php $counter = 0; @endphp
                     @if(!empty($testimonials))
                     @foreach($testimonials as $value)
                        <tr>
                           <td>#{{ ++$counter }}</td>
                           <td>{{ $value->name }}</td>
                           <td>
                              <img src="{{ displayBanner($value->image) }}" width="80" height="80">
                           </td>
                           <td>{{ Str::limit($value->description, 80) }}</td>
                           <td>
                               <a href="{{ route('slider.edit', $value->id) }}" title="{{ trans('app.actions.edit') }}">
                                 <i class="fas fa-edit text-warning"></i>
                              </a>&nbsp;|&nbsp;
                              <a href="javascript:;" onclick="commonDeleteAjax('{{ route('slider.destroy', $value->id)}}');" title="Delete section">
                                 <i class="fas fa-trash text-danger" aria-hidden="true"></i>
                              </a> 
                           </td>
                        </tr>
                     @endforeach
                     @endif
                     </tbody>
                    
                  </table>
               </div>
               <!-- /.card-body -->
            </div>
            <!-- /.card -->
         </div>
         <!-- /.col -->
      </div>
      <!-- /.row -->
   </div>
   <!-- /.container-fluid -->
</section>

@endsection